blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogCreate, BlogList, BlogDetail, BlogUpdate, BlogDelete

app_name = BlogConfig.name


urlpatterns = [
    path('blog/create/', BlogCreate.as_view(), name='blog_create'),
    path('blog/list/', BlogList.as_view(), name='blog_list'),
    path('blog/detail/<int:pk>/', cache_page(60)(BlogDetail.as_view()), name='blog_detail'),
    path('blog/update/<int:pk>/', BlogUpdate.as_view(), name='blog_update'),
    path('blog/delete/<int:pk>/', BlogDelete.as_view(), name='blog_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users')),
    path('mailings/', include('mailings.urls', namespace='mailings')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailings/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mailings.apps import MailingsConfig

from mailings.views import MessageCreate, MessageList, MessageDetail, MessageUpdate, MessageDelete, ClientCreate, \
    ClientList, ClientDetail, ClientUpdate, ClientDelete, MailingCreate, MailingList, MailingDetail, MailingUpdate, \
    MailingDelete, MailingTryList, MailingTryDetail

app_name = MailingsConfig.name


urlpatterns = [
    path('message/create/', MessageCreate.as_view(), name='message_create'),
    path('message/list/', MessageList.as_view(), name='message_list'),
    path('message/detail/<int:pk>/', cache_page(60)(MessageDetail.as_view()), name='message_detail'),
    path('message/update/<int:pk>/', MessageUpdate.as_view(), name='message_update'),
    path('message/delete/<int:pk>/', MessageDelete.as_view(), name='message_delete'),

    path('client/create/', ClientCreate.as_view(), name='client_create'),
    path('client/list/', ClientList.as_view(), name='client_list'),
    path('client/detail/<int:pk>/', cache_page(60)(ClientDetail.as_view()), name='client_detail'),
    path('client/update/<int:pk>/', ClientUpdate.as_view(), name='client_update'),
    path('client/delete/<int:pk>/', ClientDelete.as_view(), name='client_delete'),

    path('mailing/create/', MailingCreate.as_view(), name='mailing_create'),
    path('mailing/list/', MailingList.as_view(), name='mailing_list'),
    path('mailing/detail/<int:pk>/', cache_page(60)(MailingDetail.as_view()), name='mailing_detail'),
    path('mailing/update/<int:pk>/', MailingUpdate.as_view(), name='mailing_update'),
    path('mailing/delete/<int:pk>/', MailingDelete.as_view(), name='mailing_delete'),

    path('mailingtry/list/', MailingTryList.as_view(), name='mailingtry_list'),
    path('mailingtry/detail/<int:pk>/', MailingTryDetail.as_view(), name='mailingtry_detail'),
]

mailings/models.py
from django.db import models

from users.models import User

NULLABLE = {'blank': True, 'null': True}


class Message(models.Model):
    topic = models.CharField(max_length=100, verbose_name='тема')
    body = models.TextField(verbose_name='содержимое')

    owner = models.ForeignKey(User, related_name='message_owner', on_delete=models.CASCADE,
                              **NULLABLE, verbose_name='владелец')

    def __str__(self):
        return self.topic

    class Meta:
        verbose_name = 'сообщение'
        verbose_name_plural = 'сообщения'


class Client(models.Model):
    email = models.EmailField(unique=True, verbose_name='email')
    full_name = models.CharField(max_length=200, verbose_name='фио')
    comment = models.TextField(**NULLABLE)

    owner = models.ForeignKey(User, related_name='client_owner', on_delete=models.CASCADE,
                              **NULLABLE, verbose_name='владелец')

    def __str__(self):
        return self.full_name

    class Meta:
        verbose_name = 'клиент'
        verbose_name_plural = 'клиенты'


class Mailing(models.Model):

    INTERVALS = [
        ('day', 'Раз в день'),
        ('week', 'Раз в неделю'),
        ('month', 'Раз в месяц')
    ]
    STATUSES = [
        ('off', 'Отключена'),
        ('waiting_first', 'Запущена, Ожидает первой отправки'),
        ('send_waiting', 'Отправлена, ожидает следующей отправки')
    ]

    name = models.CharField(max_length=100, **NULLABLE, verbose_name='название')
    next_sending = models.DateTimeField(**NULLABLE, help_text='ГГГГ-ММ-ДД ЧЧ:ММ:СС',
                                        verbose_name='дата и время отправки')
    last_sending = models.DateTimeField(**NULLABLE, verbose_name='крайняя отправка')
    interval = models.CharField(max_length=15, choices=INTERVALS, default='month', verbose_name='периодичность')
    status = models.CharField(max_length=15, choices=STATUSES, default='off', verbose_name='статус')

    message = models.ForeignKey(Message, **NULLABLE, on_delete=models.SET_NULL, related_name='mailing_message',
                                verbose_name='сообщение рассылки')

    clients = models.ManyToManyField(Client, related_name='mailing_clients', verbose_name='клиенты рассылки')

    owner = models.ForeignKey(User, related_name='mailing_owner', on_delete=models.CASCADE,
                              **NULLABLE, verbose_name='владелец')

    def __str__(self):
        return self.name

    class Meta:

        permissions = [
            ('change_status', 'Can change status of mailing'),
        ]

        verbose_name = 'рассылка'
        verbose_name_plural = 'рассылки'
        ordering = ('next_sending',)


class MailingTry(models.Model):
    last_try = models.DateTimeField(auto_now=True, help_text='дата и время последней попытки',
                                    verbose_name='последняя попытка')
    try_status = models.BooleanField(default=False, verbose_name='статус попытки')
    email_response = models.TextField(**NULLABLE, verbose_name='ответ почтового сервера')

    mailing = models.ForeignKey(Mailing, **NULLABLE, on_delete=models.CASCADE,
                                related_name='tries_mailing', verbose_name='рассылка попытки')

    owner = models.ForeignKey(User, related_name='mailingtry_owner', on_delete=models.CASCADE,
                              **NULLABLE, verbose_name='владелец')

    class Meta:
        verbose_name = 'попытка рассылки'
        verbose_name_plural = 'попытки рассылки'
        ordering = ('last_try',)

mailings/forms.py
from django.forms import ModelForm, BooleanField

from mailings.models import Message, Client, Mailing


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class MessageForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Message
        exclude = ('owner',)


class ClientForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Client
        exclude = ('owner',)


class MailingForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Mailing
        exclude = ('owner', 'last_sending',)

    def __init__(self, *args, **kwargs):
        """Переопределяет набор объектов, отображаются только объекты текущего пользователя"""
        user = kwargs.pop('user')
        super().__init__(*args, **kwargs)
        self.fields['message'].queryset = Message.objects.filter(owner=user)
        self.fields['clients'].queryset = Client.objects.filter(owner=user)


class MailingManagerForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Mailing
        fields = ('status',)

mailings/views.py
from pytz import timezone

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.exceptions import PermissionDenied
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView

from config import settings
from mailings.forms import MessageForm, ClientForm, MailingForm, MailingManagerForm
from mailings.models import Message, Client, Mailing, MailingTry
from mailings.services import get_message_list_from_cache, get_client_list_from_cache, get_mailing_list_from_cache


# CRUD для Message ##################################################
class MessageCreate(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Message
    form_class = MessageForm
    permission_required = 'mailings.add_message'
    success_url = reverse_lazy('mailings:message_list')

    def form_valid(self, form):
        message = form.save()
        user = self.request.user
        message.owner = user
        message.save()
        return super().form_valid(form)

    def get_context_data(self, *, object_list=None, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Создание сообщения'
        return context_data


class MessageList(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = Message
    permission_required = 'mailings.view_message'

    def get_context_data(self, *, object_list=None, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Сообщения'
        context_data['object_list'] = get_message_list_from_cache()

        user = self.request.user
        if user.is_superuser:
            return context_data
        users_items = []
        for item in context_data.get('object_list'):
            if user == item.owner:
                users_items.append(item)
        context_data['object_list'] = users_items
        return context_data


class MessageDetail(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = Message
    permission_required = 'mailings.view_message'

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        user = self.request.user
        if user == self.object.owner or user.is_superuser:
            self.object.save()
            return self.object
        raise PermissionDenied

    def get_context_data(self, *, object_list=None, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Подробности сообщения'
        return context_data


class MessageUpdate(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Message
    form_class = MessageForm
    permission_required = 'mailings.change_message'

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        user = self.request.user
        if user == self.object.owner or user.is_superuser:
            self.object.save()
            return self.object
        raise PermissionDenied

    def get_success_url(self):
        return reverse('mailings:message_detail', args=[self.kwargs.get('pk')])

    def get_context_data(self, *, object_list=None, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Редактирование сообщения'
        return context_data


class MessageDelete(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Message
    permission_required = 'mailings.delete_message'
    success_url = reverse_lazy('mailings:message_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        user = self.request.user
        if user == self.object.owner or user.is_superuser:
            self.object.save()
            return self.object
        raise PermissionDenied

    def get_context_data(self, *, object_list=None, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Удаление сообщения'
        return context_data


# CRUD для Client ###################################################
class ClientCreate(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Client
    form_class = ClientForm
    permission_required = 'mailings.add_client'
    success_url = reverse_lazy('mailings:client_list')

    def form_valid(self, form):
        client = form.save()
        user = self.request.user
        client.owner = user
        client.save()
        return super().form_valid(form)

    def get_context_data(self, *, object_list=None, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Создание клиента'
        return context_data


class ClientList(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = Client
    permission_required = 'mailings.view_client'

    def get_context_data(self, *, object_list=None, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Клиенты'
        context_data['object_list'] = get_client_list_from_cache()

        user = self.request.user
        if user.is_superuser:
            return context_data
        users_items = []
        for item in context_data.get('object_list'):
            if user == item.owner:
                users_items.append(item)
        context_data['object_list'] = users_items
        return context_data


class ClientDetail(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = Client
    permission_required = 'mailings.view_client'

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        user = self.request.user
        if user == self.object.owner or user.is_superuser:
            self.object.save()
            return self.object
        raise PermissionDenied

    def get_context_data(self, *, object_list=None, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Подробности клиента'
        return context_data


class ClientUpdate(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Client
    form_class = ClientForm
    permission_required = 'mailings.change_client'

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        user = self.request.user
        if user == self.object.owner or user.is_superuser:
            self.object.save()
            return self.object
        raise PermissionDenied

    def get_success_url(self):
        return reverse('mailings:client_detail', args=[self.kwargs.get('pk')])

    def get_context_data(self, *, object_list=None, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Редактирование клиента'
        return context_data


class ClientDelete(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Client
    permission_required = 'mailings.delete_client'
    success_url = reverse_lazy('mailings:client_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        user = self.request.user
        if user == self.object.owner or user.is_superuser:
            self.object.save()
            return self.object
        raise PermissionDenied

    def get_context_data(self, *, object_list=None, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Удаление клиента'
        return context_data


# CRUD для Mailing ##################################################
class MailingCreate(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Mailing
    form_class = MailingForm
    permission_required = 'mailings.add_mailing'
    success_url = reverse_lazy('mailings:mailing_create')

    def get_form_kwargs(self):
        """Добавляем текущего пользователя в аргументы формы."""
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        mailing = form.save()
        user = self.request.user
        mailing.owner = user

        zone = timezone(settings.TIME_ZONE)
        mailing.next_sending = mailing.next_sending.replace(tzinfo=zone, microsecond=0, second=0)

        mailing.save()
        return super().form_valid(form)

    def get_context_data(self, *, object_list=None, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Создание рассылки'
        return context_data


class MailingList(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = Mailing
    permission_required = 'mailings.view_mailing'

    def get_context_data(self, *, object_list=None, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Рассылки'
        context_data['object_list'] = get_mailing_list_from_cache()

        user = self.request.user
        if user.is_superuser or user.has_perm('mailings.change_status'):
            return context_data
        users_items = []
        for item in context_data.get('object_list'):
            if user == item.owner:
                users_items.append(item)
        context_data['object_list'] = users_items
        return context_data


class MailingDetail(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = Mailing
    permission_required = 'mailings.view_mailing'

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        user = self.request.user
        if user == self.object.owner or user.has_perm('mailings.change_status'):
            self.object.save()
            return self.object
        raise PermissionDenied

    def get_context_data(self, *, object_list=None, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Подробности рассылки'

mailings/templates/mailings/client_detail.html
{% extends 'main/base.html' %}
{% block content %}
<div class="col-12">
  <div class="card mt-4">
    <div class="card-header">
      <h4>{{ object.full_name }}</h4>
    </div>
    <div class="card-body">
      Email: {{ object.email }}
      {% if object.comment %}
      <hr>
      <div class="card-text">
        <h6>Комментарий</h6>
        {{ object.comment }}
      </div>
      {% endif %}
    </div>
    <div class="card-footer">
      <div class="row col-4">
        <div class="col-4 p-1">
          <a class="btn btn-outline-secondary col-12" href="{% url 'mailings:client_list' %}">Назад</a>
        </div>
        {% if user.is_authenticated %}
        <div class="col-4 p-1">
          <a class="btn btn-outline-warning col-12" href="{% url 'mailings:client_update' object.pk %}">Изменить</a>
        </div>
        <div class="col-4 p-1">
          <a class="btn btn-outline-danger col-12" href="{% url 'mailings:client_delete' object.pk %}">Удалить</a>
        </div>
        {% endif %}
      </div>
    </div>
  </div>
</div>
{% endblock %}

mailings/templates/mailings/client_list.html
{% extends 'main/base.html' %}
{% block content %}
{% if user.is_authenticated %}
<div class="container p-0">
  <a class="btn btn-outline-success" href="{% url 'mailings:client_create' %}">Добавить клиента</a>
</div>
{% endif %}
<div class="container mt-3 p-0">
  <table class="table table-striped-columns">
    <thead>
    <tr>
      <th scope="col">id</th>
      <th scope="col">ФИО</th>
      <th scope="col">email</th>
      <th scope="col">Кнопки</th>
    </tr>
    </thead>
    <tbody>
    {% for object in object_list %}
    <tr>
      <td>{{ object.pk }}</td>
      <td>{{ object.full_name }}</td>
      <td>{{ object.email }}</td>
      <td>
        <div class="col-12 p-1">
          <a class="btn btn-outline-dark col-12" href="{% url 'mailings:client_detail' object.pk %}">Подробнее</a>
        </div>
      </td>
    </tr>
    {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

mailings/templates/mailings/mailing_confirm_delete.html
{% extends 'main/base.html' %}
{% block content %}
<div class="col-12">
  <div class="card mt-5">
    <div class="card-header">
      {{ object.name }}
    </div>
    <div class="card-body">
      Статус: {{ object.status }}<br>
      Сообщение: {{ object.message|truncatechars:15 }}
    </div>
    <div class="card-footer">
      <div class="row col-4">
        <div class="col-6 p-1">
          <form method="post">
            {% csrf_token %}
            <button class="btn btn-outline-danger col-12">Удалить</button>
          </form>
        </div>
        <div class="col-6 p-1">
          <a class="btn btn-outline-secondary col-12" href="{% url 'mailings:mailing_list' %}">Назад</a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

mailings/templates/mailings/mailing_detail.html
{% extends 'main/base.html' %}
{% block content %}
<div class="col-12">
  <div class="card mt-4">
    <div class="card-header">
      <h4>{{ object.name }}</h4>
    </div>
    <div class="card-body">
      <table class="table table-striped-columns">
        <thead>
        <tr>
          <th scope="col">id</th>
          <th scope="col">Статус</th>
          <th scope="col">Периодичность</th>
          <th scope="col">Сообщение</th>
        </tr>
        </thead>
        <tbody>
        <tr>
          <td>{{ object.pk }}</td>
          <td>{{ object.get_status_display }}</td>
          <td>{{ object.get_interval_display }}</td>
          <td>
            {% if object.message %}
            <a href="{% url 'mailings:message_detail' object.message.pk %}">{{ object.message|truncatechars:35 }}</a>
            {% else %}
            <h6>Отсутствует</h6>
            {% endif %}
          </td>
        </tr>
        </tbody>
      </table>
      {% if object.clients %}
      <h4>Клиенты</h4>
      {% for client in object.clients.all %}
      {{ client }}
      {% endfor %}
      {% endif %}
    </div>
    <div class="card-footer">
      <div class="row col-4">
        <div class="col-4 p-1">
          <a class="btn btn-outline-secondary col-12" href="{% url 'mailings:mailing_list' %}">Назад</a>
        </div>
        {% if user.is_authenticated %}
        <div class="col-4 p-1">
          <a class="btn btn-outline-warning col-12" href="{% url 'mailings:mailing_update' object.pk %}">Изменить</a>
        </div>
        <div class="col-4 p-1">
          <a class="btn btn-outline-danger col-12" href="{% url 'mailings:mailing_delete' object.pk %}">Удалить</a>
        </div>
        {% endif %}
      </div>
    </div>
  </div>
</div>
{% endblock %}

mailings/templates/mailings/mailing_form.html
{% extends 'main/base.html' %}
{% block content %}
<div class="col-12">
  <div class="card mt-5">
    <div class="card-header">
      Рассылка
    </div>
    <form method="post">
      <div class="card-body">
        {% csrf_token %}
        {{ form.as_p }}
      </div>
      <div class="card-footer">
        <div class="row col-4">
          {% if object %}
            <div class="col-6 p-1">
              <button class="btn btn-outline-success col-12">Сохранить</button>
            </div>
          {% else %}
            <div class="col-6 p-1">
              <button class="btn btn-outline-success col-12">Создать</button>
            </div>
          {% endif %}
          <div class="col-6 p-1">
            <a class="btn btn-outline-secondary col-12" href="{% url 'mailings:mailing_list' %}">Назад</a>
          </div>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock %}

mailings/templates/mailings/mailing_list.html
{% extends 'main/base.html' %}
{% block content %}
{% if perms.mailings.add_mailing %}
<div class="container p-0">
  <a class="btn btn-outline-success" href="{% url 'mailings:mailing_create' %}">Добавить рассылку</a>
</div>
{% endif %}
<div class="container mt-3 p-0">
  <table class="table table-striped-columns">
    <thead>
    <tr>
      <th scope="col">id</th>
      <th scope="col">Наименование</th>
      <th scope="col">Статус</th>
      <th scope="col">Периодичность</th>
      <th scope="col">Сообщение</th>
      <th scope="col">Кнопки</th>
    </tr>
    </thead>
    <tbody>
    {% for object in object_list %}
    <tr>
      <td>{{ object.pk }}</td>
      <td>{{ object.name|truncatechars:15 }}</td>
      <td>{{ object.get_status_display }}</td>
      <td>{{ object.get_interval_display }}</td>
      <td>
        {% if object.message %}
        {{ object.message|truncatechars:15 }}
        {% else %}
        <h6>Отсутствует</h6>
        {% endif %}
      </td>
      <td>
        <div class="col-12 p-1">
          <a class="btn btn-outline-dark col-12" href="{% url 'mailings:mailing_detail' object.pk %}">Подробнее</a>
        </div>
      </td>
    </tr>
    {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

mailings/templates/mailings/mailingtry_detail.html
{% extends 'main/base.html' %}
{% block content %}
<div class="col-12">
  <div class="card mt-4">
    <div class="card-header">
      <h4>Наименование: {{ object.name }}</h4>
    </div>
    <div class="card-body">
      <table class="table table-striped-columns">
        <thead>
        <tr>
          <th scope="col">id</th>
          <th scope="col">Дата попытки</th>
          <th scope="col">Рассылка</th>
          <th scope="col">Статус</th>
        </tr>
        </thead>
        <tbody>
        <tr>
          <td>{{ object.pk }}</td>
          <td>{{ object.last_try }}</td>
          <td>
            {% if object.mailing %}
            <a href="{% url 'mailings:mailing_detail' object.mailing.pk %}">{{ object.mailing }}</a>
            {% else %}
            <h6>Отсутствует</h6>
            {% endif %}
          </td>
          <td>{{ object.try_status }}</td>
        </tr>
        </tbody>
      </table>
      {% if object.email_response %}
      <h4>Ответ почтового сервиса</h4>
        {{ object.email_response }}
      {% endif %}
    </div>
    <div class="card-footer">
      <div class="row col-4">
        <div class="col-4 p-1">
          <a class="btn btn-outline-secondary col-12" href="{% url 'mailings:mailingtry_list' %}">Назад</a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

mailings/templates/mailings/mailingtry_list.html
{% extends 'main/base.html' %}
{% block content %}
<div class="container mt-3 p-0">
  <table class="table table-striped-columns">
    <thead>
    <tr>
      <th scope="col">id</th>
      <th scope="col">Наименование</th>
      <th scope="col">Дата попытки</th>
      <th scope="col">Рассылка</th>
      <th scope="col">Статус</th>
      <th scope="col">Кнопки</th>
    </tr>
    </thead>
    <tbody>
    {% for object in object_list %}
    <tr>
      <td>{{ object.pk }}</td>
      <td>{{ object.name }}</td>
      <td>{{ object.last_try }}</td>
      <td>{{ object.mailing }}</td>
      <td>{{ object.try_status }}</td>
      <td>
        <div class="col-12 p-1">
          <a class="btn btn-outline-dark col-12" href="{% url 'mailings:mailingtry_detail' object.pk %}">Подробнее</a>
        </div>
      </td>
    </tr>
    {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

mailings/templates/mailings/message_detail.html
{% extends 'main/base.html' %}
{% block content %}
<div class="col-12">
  <div class="card mt-4">
    <div class="card-header">
      <h4>{{ object.topic }}</h4>
    </div>
    <div class="card-body">
      {{ object.body }}
    </div>
    <div class="card-footer">
      <div class="row col-4">
        <div class="col-4 p-1">
          <a class="btn btn-outline-secondary col-12" href="{% url 'mailings:message_list' %}">Назад</a>
        </div>
        {% if user.is_authenticated %}
        <div class="col-4 p-1">
          <a class="btn btn-outline-warning col-12" href="{% url 'mailings:message_update' object.pk %}">Изменить</a>
        </div>
        <div class="col-4 p-1">
          <a class="btn btn-outline-danger col-12" href="{% url 'mailings:message_delete' object.pk %}">Удалить</a>
        </div>
        {% endif %}
      </div>
    </div>
  </div>
</div>
{% endblock %}

mailings/templates/mailings/message_list.html
{% extends 'main/base.html' %}
{% block content %}
{% if user.is_authenticated %}
<div class="container p-0">
  <a class="btn btn-outline-success" href="{% url 'mailings:message_create' %}">Добавить сообщение</a>
</div>
{% endif %}
<div class="row">
  {% for object in object_list %}
  <div class="col-4">
    <div class="card mt-4">
      <div class="card-header">
        <h6>{{ object.topic|truncatechars:40 }}</h6>
      </div>
      <div class="card-body" style="height:250px">
        <p>{{ object.body|truncatechars:360 }}</p>
      </div>
      <div class="card-footer">
        <div class="row">
          <div class="col-12 p-1">
            <a class="btn btn-outline-dark col-12" href="{% url 'mailings:message_detail' object.pk %}">Подробнее</a>
          </div>
        </div>
        {% if user.is_authenticated %}
        <div class="row">
          <div class="col-6 p-1">
            <a class="btn btn-outline-warning col-12" href="{% url 'mailings:message_update' object.pk %}">Изменить</a>
          </div>
          <div class="col-6 p-1">
            <a class="btn btn-outline-danger col-12" href="{% url 'mailings:message_delete' object.pk %}">Удалить</a>
          </div>
        </div>
        {% endif %}
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}