blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogCreate, BlogList, BlogDetail, BlogUpdate, BlogDelete

app_name = BlogConfig.name


urlpatterns = [
    path('blog/create/', BlogCreate.as_view(), name='blog_create'),
    path('blog/list/', BlogList.as_view(), name='blog_list'),
    path('blog/detail/<int:pk>/', cache_page(60)(BlogDetail.as_view()), name='blog_detail'),
    path('blog/update/<int:pk>/', BlogUpdate.as_view(), name='blog_update'),
    path('blog/delete/<int:pk>/', BlogDelete.as_view(), name='blog_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users')),
    path('mailings/', include('mailings.urls', namespace='mailings')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

from users.models import User

NULLABLE = {'blank': True, 'null': True}


class Blog(models.Model):
    title = models.CharField(max_length=200, verbose_name='заголовок')
    body = models.TextField(verbose_name='содержимое')
    image = models.ImageField(upload_to='blog/image', **NULLABLE, verbose_name='изображение')
    views_count = models.PositiveIntegerField(default=0, verbose_name='счетчик просмотров')
    publish_date = models.DateField(auto_now=True, verbose_name='дата публикации')
    is_published = models.BooleanField(default=True, verbose_name='признак публикации')

    owner = models.ForeignKey(User, on_delete=models.CASCADE, **NULLABLE, related_name='blog_owner',
                              verbose_name='владелец')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'блог'
        verbose_name_plural = 'блоги'
        ordering = ('title', 'views_count',)

blog/forms.py
from django import forms

from blog.models import Blog
from mailings.forms import StyleFormMixin


class BlogForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Blog
        fields = ('title', 'body', 'image',)

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.exceptions import PermissionDenied
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView

from blog.forms import BlogForm
from blog.models import Blog
from blog.services import get_blog_list_from_cache


# CRUD для Blog #####################################################
class BlogCreate(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Blog
    form_class = BlogForm
    permission_required = 'blog.add_blog'
    success_url = reverse_lazy('blog:blog_create')

    def form_valid(self, form):
        blog = form.save()
        user = self.request.user
        blog.owner = user
        blog.save()
        return super().form_valid(form)

    def get_context_data(self, *, object_list=None, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Создание блога'
        return context_data


class BlogList(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = Blog
    permission_required = 'blog.view_blog'

    def get_context_data(self, *, object_list=None, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Блоги'
        context_data['object_list'] = get_blog_list_from_cache()
        return context_data


class BlogDetail(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = Blog
    permission_required = 'blog.view_blog'

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object

    def get_context_data(self, *, object_list=None, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Подробности блога'
        return context_data


class BlogUpdate(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Blog
    form_class = BlogForm
    permission_required = 'blog.change_blog'

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        user = self.request.user
        if user == self.object.owner or user.is_superuser:
            self.object.save()
            return self.object
        raise PermissionDenied

    def get_success_url(self):
        return reverse('blog:blog_detail', args=[self.kwargs.get('pk')])

    def get_context_data(self, *, object_list=None, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Редактирование блога'
        return context_data


class BlogDelete(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Blog
    permission_required = 'blog.delete_blog'
    success_url = reverse_lazy('blog:blog_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        user = self.request.user
        if user == self.object.owner or user.is_superuser:
            self.object.save()
            return self.object
        raise PermissionDenied

    def get_context_data(self, *, object_list=None, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Удаление блога'
        return context_data

blog/templates/blog/blog_confirm_delete.html
{% extends 'main/base.html' %}
{% block content %}
<div class="col-4">
  <div class="card mt-4">
    <div class="card-header">
      {{ object.title|truncatechars:40 }}
    </div>
    <div class="card-footer">
      <div class="row col-12">
        <div class="col-6 p-1">
          <form method="post">
            {% csrf_token %}
            <button class="btn btn-outline-danger col-12">Удалить</button>
          </form>
        </div>
        <div class="col-6 p-1">
          <a class="btn btn-outline-secondary col-12" href="{% url 'blog:blog_list' %}">Назад</a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'main/base.html' %}
{% block content %}
{% load custom_tags %}
<div class="col-12">
  <h2 class="text-center">{{ object.title }}</h2>
  <img class=" mt-3" src="{{object.image | media_filter}}" style="width: 100%; height: 20rem;">
  <p class="mt-3">{{ object.body }}</p>
    <div class="row col-4">
    <div class="col-4 p-1">
      <a class="btn btn-outline-secondary col-12" href="{% url 'blog:blog_list' %}">Назад</a>
    </div>
    {% if perms.blog.change_blog%}
    <div class="col-4 p-1">
      <a class="btn btn-outline-warning col-12" href="{% url 'blog:blog_update' object.pk %}">Изменить</a>
    </div>
    {% endif %}
    {% if perms.blog.delete_blog%}
    <div class="col-4 p-1">
      <a class="btn btn-outline-danger col-12" href="{% url 'blog:blog_delete' object.pk %}">Удалить</a>
    </div>
    {% endif %}
</div>
</div>

{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'main/base.html' %}
{% block content %}
<div class="col-12">
  <div class="card mt-3">
    <div class="card-header">
      Блог
    </div>
    <form method="post" enctype="multipart/form-data">
      <div class="card-body">
        {% csrf_token %}
        {{ form.as_p }}
      </div>
      <div class="card-footer">
        <div class="row col-4">
          {% if object %}
            <div class="col-6 p-1">
              <button class="btn btn-outline-success col-12">Сохранить</button>
            </div>
          {% else %}
            <div class="col-6 p-1">
              <button class="btn btn-outline-success col-12">Создать</button>
            </div>
          {% endif %}
          <div class="col-6 p-1">
            <a class="btn btn-outline-secondary col-12" href="{% url 'blog:blog_list' %}">Назад</a>
          </div>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'main/base.html' %}
{% block content %}
{% load custom_tags %}
{% if perms.blog.add_blog %}
<div class="container p-0">
  <a class="btn btn-outline-success" href="{% url 'blog:blog_create' %}">Добавить блог</a>
</div>
{% endif %}
<div class="row">
  {% for object in object_list %}
  <div class="col-6">
    <div class="card mt-4">
      <div class="card-header">
        <h6>{{ object.title|truncatechars:40 }}</h6>
      </div>
      <div class="card-body" style="height:275px">
        <div class="row">
          <div class="col-5">
            <img src="{{object.image | media_filter}}" style="width: 15rem; height: 15rem;">
          </div>
          <div class="col-7">
            <p>{{ object.body|truncatechars:280 }}</p>
          </div>
        </div>
      </div>
      <div class="card-footer">
        <div class="row">
          <div class="col-12 p-1">
            <a class="btn btn-outline-dark col-12" href="{% url 'blog:blog_detail' object.pk %}">Подробнее</a>
          </div>
        </div>
        <div class="row">
          {% if perms.blog.change_blog%}
          <div class="col-6 p-1">
            <a class="btn btn-outline-warning col-12" href="{% url 'blog:blog_update' object.pk %}">Изменить</a>
          </div>
          {% endif %}
          {% if perms.blog.delete_blog%}
          <div class="col-6 p-1">
            <a class="btn btn-outline-danger col-12" href="{% url 'blog:blog_delete' object.pk %}">Удалить</a>
          </div>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}