blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogCreate, BlogList, BlogDetail, BlogUpdate, BlogDelete

app_name = BlogConfig.name


urlpatterns = [
    path('blog/create/', BlogCreate.as_view(), name='blog_create'),
    path('blog/list/', BlogList.as_view(), name='blog_list'),
    path('blog/detail/<int:pk>/', cache_page(60)(BlogDetail.as_view()), name='blog_detail'),
    path('blog/update/<int:pk>/', BlogUpdate.as_view(), name='blog_update'),
    path('blog/delete/<int:pk>/', BlogDelete.as_view(), name='blog_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users')),
    path('mailings/', include('mailings.urls', namespace='mailings')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main.apps import MainConfig
from main.views import IndexTemplate

app_name = MainConfig.name

urlpatterns = [
    path('', IndexTemplate.as_view(), name='index'),
]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from users.apps import UsersConfig

from users.views import UserRegister, email_verification, UserLogin, UserProfileUpdate, UserList, UserDetail, \
    UserUpdate, UserProfile

app_name = UsersConfig.name


urlpatterns = [
    path('login/', UserLogin.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserRegister.as_view(), name='register'),
    path('email-confirm/<str:token>/', email_verification, name='email_confirm'),
    path('list/', UserList.as_view(), name='user_list'),
    path('detail/<int:pk>/', UserDetail.as_view(), name='user_detail'),
    path('update/<int:pk>/', UserUpdate.as_view(), name='user_update'),
    path('profile', UserProfile.as_view(), name='profile'),
    path('change-profile', UserProfileUpdate.as_view(), name='profile_update'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='email')

    token = models.CharField(max_length=50, **NULLABLE, verbose_name='token')

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    class Meta:
        permissions = [
            ('change_is_active', 'Can change is_active of user'),
        ]

        verbose_name = 'пользователь'
        verbose_name_plural = 'пользователи'

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm

from mailings.forms import StyleFormMixin
from users.models import User


class UserCreateForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2',)


class UserLoginForm(StyleFormMixin, AuthenticationForm):
    pass


class UserProfileForm(StyleFormMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()


class UserProfileManagerForm(StyleFormMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ('is_active',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()
        self.fields['is_active'].help_text = 'Чтобы заблокировать пользователя - уберите галочку'

users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.models import Group
from django.core.exceptions import PermissionDenied
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, ListView, DetailView
from django.contrib.auth.views import LoginView

from users.forms import UserCreateForm, UserLoginForm, UserProfileForm, UserProfileManagerForm
from users.models import User
from users.services import send_email_verification_message


class UserLogin(LoginView):
    template_name = 'users/login.html'
    form_class = UserLoginForm

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Авторизация'
        return context_data


# Create, Read, Update для User #####################################
class UserRegister(CreateView):
    model = User
    form_class = UserCreateForm
    success_url = reverse_lazy('main:index')

    def form_valid(self, form):
        user = form.save()
        send_email_verification_message(self, user)
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Регистрация'
        return context_data


def email_verification(request, token):
    user = get_object_or_404(User, token=token)

    user_group = Group.objects.get(name='user')
    user_group.user_set.add(user)

    user.is_active = True
    user.save()
    return redirect('users:login')


class UserList(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = User
    permission_required = 'users.view_user'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Пользователи'
        user = self.request.user
        context['object_list'] = User.objects.exclude(is_superuser=True).exclude(pk=user.pk)
        return context


class UserDetail(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = User
    permission_required = 'users.view_user'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Подробности пользователя'
        return context


class UserProfile(LoginRequiredMixin, DetailView):
    model = User
    template_name = 'users/profile.html'

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Профиль'
        return context


class UserProfileUpdate(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = User
    form_class = UserProfileForm
    permission_required = 'users.change_user'
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Редактирование профиля'
        return context


class UserUpdate(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = User
    permission_required = ('users.change_user', 'users.change_is_active',)
    success_url = reverse_lazy('users:user_list')

    def get_form_class(self):
        user = self.request.user
        if user.has_perm('users.change_is_active'):
            return UserProfileManagerForm
        else:
            raise PermissionDenied

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Редактирование пользователя'
        user = self.request.user
        if context['object'].pk == user.pk:
            raise PermissionDenied
        return context

users/templates/users/login.html
{% extends 'main/base.html' %}
{% block content %}
<div class="container col-6">
  <div class="card mt-5">
    <form method="post">
      <div class="card-body">
        {% csrf_token %}
        {{ form.as_p }}
      </div>
      <div class="card-footer">
        <div class="row col-12">
          <div class="col-6 p-1">
            <button class="btn btn-outline-success col-12" type="submit">Войти</button>
          </div>
          <div class="col-6 p-1">
            <a class="btn btn-outline-secondary col-12" href="{% url 'main:index' %}">На главную</a>
          </div>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock %}

users/templates/users/profile.html
{% extends 'main/base.html' %}
{% block content %}
<div class="container col-6">
  <div class="card mt-5">
    {% if object.first_name or object.last_name %}
    <div class="card-header">
      <h4>{{ object.first_name }} {{ object.last_name }}</h4>
    </div>
    {% endif %}
    <div class="card-body">
      {{ object.email }}
    </div>
    <div class="card-footer">
      <div class="row col-12">
        <div class="col-6 p-1">
          <a class="btn btn-outline-success col-12" href="{% url 'users:profile_update' %}">Редактировать профиль</a>
        </div>
        <div class="col-6 p-1">
          <a class="btn btn-outline-secondary col-12" href="{% url 'main:index' %}">На главную</a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

users/templates/users/user_detail.html
{% extends 'main/base.html' %}
{% block content %}
<div class="container col-6">
  <div class="card mt-5">
    {% if object.first_name or object.last_name %}
    <div class="card-header">
      <h4>{{ object.first_name }} {{ object.last_name }}</h4>
    </div>
    {% endif %}
    <div class="card-body">
      {{ object.email }}
    </div>
    <div class="card-footer">
      <div class="row col-12">
        <div class="col-6 p-1">
          <a class="btn btn-outline-success col-12" href="{% url 'users:user_update' object.pk %}">Редактировать профиль</a>
        </div>
        <div class="col-6 p-1">
          <a class="btn btn-outline-secondary col-12" href="{% url 'main:index' %}">На главную</a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'main/base.html' %}
{% block content %}
<div class="container col-6">
  <div class="card mt-5">
    {% if object.first_name or object.last_name %}
    <div class="card-header">
      <h4>{{ object.first_name }} {{ object.last_name }}</h4>
    </div>
    {% endif %}
    <form method="post">
      <div class="card-body">
        {% csrf_token %}
        {{ form.as_p }}
      </div>
      <div class="card-footer">
        <div class="row col-12">
          {% if object %}
          <div class="col-6 p-1">
            <button class="btn btn-outline-success col-12">Сохранить изменения</button>
          </div>
          {% else %}
          <div class="col-6 p-1">
            <button class="btn btn-outline-success col-12">Зарегистрироваться</button>
          </div>
          {% endif %}
          <div class="col-6 p-1">
            <a class="btn btn-outline-secondary col-12" href="{% url 'main:index' %}">На главную</a>
          </div>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock %}

users/templates/users/user_list.html
{% extends 'main/base.html' %}
{% block content %}
<div class="container mt-3 p-0">
  <table class="table table-striped-columns">
    <thead>
    <tr>
      <th scope="col">id</th>
      <th scope="col">email</th>
      <th scope="col">Активен</th>
      <th scope="col">Кнопки</th>
    </tr>
    </thead>
    <tbody>
    {% for object in object_list %}
    <tr>
      <td>{{ object.pk }}</td>
      <td>{{ object.email }}</td>
      <td>{{ object.is_active }}</td>
      <td>
        <div class="col-12 p-1">
          <a class="btn btn-outline-dark col-12" href="{% url 'users:user_detail' object.pk %}">Подробнее</a>
        </div>
      </td>
    </tr>
    {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}