blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogCreate, BlogList, BlogDetail, BlogUpdate, BlogDelete

app_name = BlogConfig.name


urlpatterns = [
    path('blog/create/', BlogCreate.as_view(), name='blog_create'),
    path('blog/list/', BlogList.as_view(), name='blog_list'),
    path('blog/detail/<int:pk>/', cache_page(60)(BlogDetail.as_view()), name='blog_detail'),
    path('blog/update/<int:pk>/', BlogUpdate.as_view(), name='blog_update'),
    path('blog/delete/<int:pk>/', BlogDelete.as_view(), name='blog_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users')),
    path('mailings/', include('mailings.urls', namespace='mailings')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailings/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mailings.apps import MailingsConfig

from mailings.views import MessageCreate, MessageList, MessageDetail, MessageUpdate, MessageDelete, ClientCreate, \
    ClientList, ClientDetail, ClientUpdate, ClientDelete, MailingCreate, MailingList, MailingDetail, MailingUpdate, \
    MailingDelete, MailingTryList, MailingTryDetail

app_name = MailingsConfig.name


urlpatterns = [
    path('message/create/', MessageCreate.as_view(), name='message_create'),
    path('message/list/', MessageList.as_view(), name='message_list'),
    path('message/detail/<int:pk>/', cache_page(60)(MessageDetail.as_view()), name='message_detail'),
    path('message/update/<int:pk>/', MessageUpdate.as_view(), name='message_update'),
    path('message/delete/<int:pk>/', MessageDelete.as_view(), name='message_delete'),

    path('client/create/', ClientCreate.as_view(), name='client_create'),
    path('client/list/', ClientList.as_view(), name='client_list'),
    path('client/detail/<int:pk>/', cache_page(60)(ClientDetail.as_view()), name='client_detail'),
    path('client/update/<int:pk>/', ClientUpdate.as_view(), name='client_update'),
    path('client/delete/<int:pk>/', ClientDelete.as_view(), name='client_delete'),

    path('mailing/create/', MailingCreate.as_view(), name='mailing_create'),
    path('mailing/list/', MailingList.as_view(), name='mailing_list'),
    path('mailing/detail/<int:pk>/', cache_page(60)(MailingDetail.as_view()), name='mailing_detail'),
    path('mailing/update/<int:pk>/', MailingUpdate.as_view(), name='mailing_update'),
    path('mailing/delete/<int:pk>/', MailingDelete.as_view(), name='mailing_delete'),

    path('mailingtry/list/', MailingTryList.as_view(), name='mailingtry_list'),
    path('mailingtry/detail/<int:pk>/', MailingTryDetail.as_view(), name='mailingtry_detail'),
]

main/urls.py
from django.urls import path

from main.apps import MainConfig
from main.views import IndexTemplate

app_name = MainConfig.name

urlpatterns = [
    path('', IndexTemplate.as_view(), name='index'),
]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from users.apps import UsersConfig

from users.views import UserRegister, email_verification, UserLogin, UserProfileUpdate, UserList, UserDetail, \
    UserUpdate, UserProfile

app_name = UsersConfig.name


urlpatterns = [
    path('login/', UserLogin.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserRegister.as_view(), name='register'),
    path('email-confirm/<str:token>/', email_verification, name='email_confirm'),
    path('list/', UserList.as_view(), name='user_list'),
    path('detail/<int:pk>/', UserDetail.as_view(), name='user_detail'),
    path('update/<int:pk>/', UserUpdate.as_view(), name='user_update'),
    path('profile', UserProfile.as_view(), name='profile'),
    path('change-profile', UserProfileUpdate.as_view(), name='profile_update'),
]

blog/models.py
from django.db import models

from users.models import User

NULLABLE = {'blank': True, 'null': True}


class Blog(models.Model):
    title = models.CharField(max_length=200, verbose_name='заголовок')
    body = models.TextField(verbose_name='содержимое')
    image = models.ImageField(upload_to='blog/image', **NULLABLE, verbose_name='изображение')
    views_count = models.PositiveIntegerField(default=0, verbose_name='счетчик просмотров')
    publish_date = models.DateField(auto_now=True, verbose_name='дата публикации')
    is_published = models.BooleanField(default=True, verbose_name='признак публикации')

    owner = models.ForeignKey(User, on_delete=models.CASCADE, **NULLABLE, related_name='blog_owner',
                              verbose_name='владелец')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'блог'
        verbose_name_plural = 'блоги'
        ordering = ('title', 'views_count',)

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='email')

    token = models.CharField(max_length=50, **NULLABLE, verbose_name='token')

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    class Meta:
        permissions = [
            ('change_is_active', 'Can change is_active of user'),
        ]

        verbose_name = 'пользователь'
        verbose_name_plural = 'пользователи'

main/views.py
from django.views.generic import TemplateView

from main.services import get_all_mailings_len_from_cache, get_active_mailings_len_from_cache, \
    get_all_clients_len_from_cache, get_popular_blogs_from_cache


class IndexTemplate(TemplateView):
    template_name = 'main/index.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Главная'

        context_data['all_mailings_len'] = get_all_mailings_len_from_cache()
        context_data['active_mailings_len'] = get_active_mailings_len_from_cache()
        context_data['all_clients_len'] = get_all_clients_len_from_cache()
        context_data['popular_blogs'] = get_popular_blogs_from_cache()
        return context_data

main/templates/main/includes/inc_navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'main:index' %}">Главная</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
              data-bs-target="#navbarNavDarkDropdown" aria-controls="navbarNavDarkDropdown" aria-expanded="false"
              aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
        {% if user.is_authenticated %}
        <ul class="navbar-nav">
          {% if user.is_superuser or perms.mailings.view_message %}
          <li class="nav-item dropdown">
            <button class="btn btn-dark dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
              Рассылки
            </button>
            <ul class="dropdown-menu dropdown-menu-dark">
              {% if perms.mailings.view_mailing %}
              <li><a class="dropdown-item" href="{% url 'mailings:mailing_list' %}">Рассылки</a></li>
              {% endif %}
              {% if perms.mailings.view_mailingtry %}
              <li><a class="dropdown-item" href="{% url 'mailings:mailingtry_list' %}">Статистика</a></li>
              {% endif %}
            </ul>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="btn btn-dark" aria-expanded="false" href="{% url 'mailings:mailing_list' %}">
              Рассылки
            </a>
          </li>
          {% endif %}
        </ul>
        {% endif %}
        <ul class="navbar-nav">
          <li class="nav-item">
            {% if perms.mailings.view_message %}
            <a class="btn btn-dark" aria-expanded="false" href="{% url 'mailings:message_list' %}">
              Сообщения
            </a>
            {% endif %}
          </li>
          <li class="nav-item">
            {% if perms.mailings.view_client %}
            <a class="btn btn-dark" aria-expanded="false" href="{% url 'mailings:client_list' %}">
              Клиенты
            </a>
            {% endif %}
          </li>
          {% if user.is_authenticated and perms.blog.view_blog %}
          <li class="nav-item">
            <a class="btn btn-dark" aria-expanded="false" href="{% url 'blog:blog_list' %}">
              Статьи
            </a>
          </li>
          {% endif %}
          {% if perms.users.view_user %}
          <li class="nav-item">
            <a class="btn btn-dark" aria-expanded="false" href="{% url 'users:user_list' %}">
              Пользователи
            </a>
          </li>
          {% endif %}
        </ul>
        <ul class="navbar-nav">
          <li class="nav-item dropdown">
            <button class="btn btn-dark dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
              {% if user.is_authenticated %}
                {{ user }}
              {% else %}
                Авторизация
              {% endif %}
            </button>
            <ul class="dropdown-menu dropdown-menu-dark">
              {% if user.is_authenticated %}
                {% if user.is_superuser %}
                <li><a class="dropdown-item" href="http://127.0.0.1:8000/admin/">Админка</a></li>
                {% endif %}
                <li><a class="dropdown-item" href="{% url 'users:profile' %}">Профиль</a></li>
                <li><a class="dropdown-item" href="{% url 'users:logout' %}">Выйти</a></li>
              {% else %}
                <li><a class="dropdown-item" href="{% url 'users:login' %}">Войти</a></li>
                <li><a class="dropdown-item" href="{% url 'users:register' %}">Регистрация</a></li>
              {% endif %}
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>